# IoX integration services
#
# Targeted-entity services controlling many entities in one call is not
# recommended — it may flood the controller with requests. To control
# multiple devices, define a scene on the controller and target that.

send_node_command:
  target:
    entity:
      integration: udi_iox
  fields:
    command:
      required: true
      selector:
        select:
          options:
            - "beep"
            - "brighten"
            - "dim"
            - "disable"
            - "enable"
            - "fade_down"
            - "fade_stop"
            - "fade_up"
            - "fast_off"
            - "fast_on"
            - "query"

get_node_commands:
  target:
    entity:
      integration: udi_iox

rename_node:
  target:
    entity:
      integration: udi_iox
  fields:
    name:
      required: true
      example: "Hallway Dimmer"
      selector:
        text:

system_query:
  fields:
    address:
      example: "1A 2B 3C 1"
      selector:
        text:
    isy:
      example: "00:21:b9:01:23:45"
      selector:
        text:

set_variable:
  fields:
    address:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 255
    type:
      required: true
      example: 2
      selector:
        select:
          options:
            - "1"
            - "2"
    value:
      required: true
      example: 100
      selector:
        number:
          min: -2147483648
          max: 2147483647
          mode: box
    init:
      default: false
      selector:
        boolean:
    isy:
      example: "00:21:b9:01:23:45"
      selector:
        text:

send_program_command:
  fields:
    address:
      example: "04B1"
      selector:
        text:
    name:
      example: "My Program"
      selector:
        text:
    command:
      required: true
      selector:
        select:
          options:
            - "disable"
            - "disable_run_at_startup"
            - "enable"
            - "enable_run_at_startup"
            - "run"
            - "run_else"
            - "run_then"
            - "stop"
    isy:
      example: "00:21:b9:01:23:45"
      selector:
        text:

run_network_resource:
  fields:
    address:
      example: 1
      selector:
        number:
          min: 1
          max: 255
    name:
      example: "My Resource"
      selector:
        text:
    isy:
      example: "00:21:b9:01:23:45"
      selector:
        text:
